/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openamedia_recorder_ARecorder */

#ifndef _Included_com_openamedia_recorder_ARecorder
#define _Included_com_openamedia_recorder_ARecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    setParameter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetOutputFile
  (JNIEnv *, jobject, jstring);
	
/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeSetPrevew
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetPreview
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeSetChannels
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetChannels
  (JNIEnv *, jobject, jint);

	/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeSetSampleRate
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetSampleRate
  (JNIEnv *, jobject, jint);

	/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeSetVideoSize
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetVideoSize
  (JNIEnv *, jobject, jint, jint);

	/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeSetColorFormat
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetColorFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeWriteVideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeWriteVideo
  (JNIEnv *, jobject, jbyteArray, jint);


/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    setParameter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_setParameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeSetup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeSetup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openamedia_recorder_ARecorder
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openamedia_recorder_ARecorder_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
